name       : haskell-hit
version    : 0.6.3
release    : 2
source     :
    - http://hackage.haskell.org/package/hit-0.6.3/hit-0.6.3.tar.gz : db86b3712029a4e40d1306dd6cc9ca2c9f4c77fe65a2b74106f1cbd2de26e471
license    : BSD-3-Clause
component  : programming.haskell
summary    : An haskell implementation of git storage operations, allowing users to
    manipulate git repositories (read and write).
description: "An haskell implementation of git storage operations, allowing users\
    \ to manipulate git repositories (read and write). \n"
builddeps  :
    - haskell-attoparsec
    - haskell-cabal-install
    - haskell-cryptohash
    - haskell-hourglass
    - haskell-mtl
    - haskell-parsec
    - haskell-patience
    - haskell-random
    - haskell-system-fileio
    - haskell-system-filepath
    - haskell-unix-compat
    - haskell-utf8-string
    - haskell-vector
    - haskell-zlib-bindings
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
